### ISSUE TITLE
video

### ISSUE THREAD

**Issue by kittenvr** [jaszlo/Playerautoma#1]
could you put video of this mod in the readme.md

**Comment by jaszlo** [comment]
What should the video show? Do you mean a video showcasing the mod?

**Comment by jaszlo** [comment]
I can create a video showcasing the mod in the future. At the moment I do not have the time for that. But thank you for the feedback!

**Comment by jaszlo** [comment]
@kittenvr A video has been added [:)](https://www.youtube.com/watch?v=FE1yiPbejaU)
