### ISSUE TITLE
Baritone and client's commands

### ISSUE THREAD

**Issue by Schnell1337** [jaszlo/Playerautoma#10]
Hey! I like your mod, it's very useful to me, but unfortunately replay can't write server commands and start/stop baritone when I need it, if you add it, I'll pay you $50, just like that

**Comment by jaszlo** [comment]
Thank you for your message. I'm glad to hear that the mod is useful to you. However, as discussed in earlier issues and outlined in the known issues section [here](https://github.com/jaszlo/Playerautoma/issues/8), I will not add recording chat activity as a feature. This decision is to prevent the mod from being abused as a spam bot.
