### ISSUE TITLE
Adding commands to controll the PlayerController

### ISSUE THREAD

**Issue by Schnell1337** [jaszlo/Playerautoma#11]
Could you create commands to use the mod, in addition to keyboard binds? No text in the chat only commands and please give me your discord or other contact link, I have a few questions so as not to stuff the github

**Comment by jaszlo** [comment]
I can and probably will add commands to control the PlayerController. However, I don't know when I will find the time to do so. If you want to contact me, feel free to do so via [Discord](https://discord.gg/kq9rz8a325). Also, feel free to implement the feature yourself and create a pull request.

**Comment by jaszlo** [comment]
Added commands with the newest version. Release can be found on [GitHub](https://github.com/jaszlo/Playerautoma/releases/tag/v0.4.3%2B1.20.4) or [Modrinth](https://modrinth.com/mod/playerautoma/version/v0.4.3+1.20.4).
