### ISSUE TITLE
Typing in chat and command start suggestion

### ISSUE THREAD

**Issue by sacdj1** [jaszlo/Playerautoma#13]
Firstly i do like the mod and hope it gets more features in the future

I would like for an option of recording anything typed in chat

And the ability to start a recorded replay via a / command

Also a way to start a replay of a recording on certain player actions say as the player dies (mostly just player death)

**Comment by jaszlo** [comment]
As mentioned [earlier](https://github.com/jaszlo/Playerautoma/issues/8), I won't add the ability to record and replay chat activity to prevent the mod from being used as a spam bot. However, I will add the ability to record commands (excluding '/say' and other common communication commands). This feature will be available in the next few days.

Currently, you can start and stop recordings and replays with /record start|stop and /replay start|stop.

The idea of a trigger system has been requested before and is something I'm considering. It's a larger addition, so I can't guarantee when or if it will be implemented.

Hope this helps. If you have any other requests, please let me know!

**Comment by jaszlo** [comment]
Commands can now be recorded in the [newest version](https://github.com/jaszlo/Playerautoma/releases/tag/v0.4.6%2B1.20.6) of the mod. Again a trigger system will follow maybe in the future and chat activity itself will not be added.
