### ISSUE TITLE
Record game chat

### ISSUE THREAD

**Issue by BoNuong** [jaszlo/Playerautoma#19]
Uh is it possible to add things like chat, command in this mod ?

**Comment by jaszlo** [comment]
[Commands](https://github.com/jaszlo/Playerautoma/issues/13#issuecomment-2131318892) can be recorded.
[Typing](https://github.com/jaszlo/Playerautoma/issues/8#issue-21151898649) in chat won't be recorded to prevent the mod from being used as a spam bot
