### ISSUE TITLE
Adding commands and chest looting

### ISSUE THREAD

**Issue by kittenvr** [jaszlo/Playerautoma#2]
doesnt do commands, doesnt take out of chests

**Comment by jaszlo** [comment]
The mod has no commands yet.  Are you asking for commands that do the same as the key binds and the GUI-Buttons? Or are you requesting different functionality? Please specify in more detail.

Also the mod only automates *Playermovement*, *Playerslotselection* and *Blockplacing*. Automating taking items out of a chest is a feature that will probably not be supported in future versions. That however is probably not my definit position on this. 

Also feel free to implement it yourself and open a pull request as I have other project with which I'm very busy right now :)

**Comment by jaszlo** [comment]
@kittenvr The feature to record/replay chest lotting,  item crafting and in general all inventory/chest activity has been added in the [latest version](https://modrinth.com/mod/playerautoma/version/wx4FZ4X4)

**Comment by kittenvr** [comment]
thank you
