### ISSUE TITLE
Can't find Discord

### ISSUE THREAD

**Issue by kittenvr** [jaszlo/Playerautoma#23]
where are the examples located?

**Comment by jaszlo** [comment]
Please be more explicit what kind of exampels you're talking about?

**Comment by kittenvr** [comment]
I don't have your discord

**Comment by jaszlo** [comment]
You can just join on the link on [modrinth](https://modrinth.com/mod/playerautoma). Please tell me which and what kind of examples  do you mean?
![image](https://github.com/user-attachments/assets/e9d9cd56-9f1f-4032-8624-da3ab3c263e1)
