### ISSUE TITLE
Request : Add a keybind to Pause / Resume the replay you are actually playing

### ISSUE THREAD

**Issue by FullHDReady** [jaszlo/Playerautoma#6]
Hello, thank you for this amazing mod

Pretty much the title, it will be an awesome addition to have the ability to pause and resume a replay you are actually playing.

Thank you !

**Comment by jaszlo** [comment]
I agree! This would be indeed a good addition. I will add this in the next updates. The issues will stay open until I have added this feature. I Will notify you via a new comment tagging you and the new release :)

**Comment by FullHDReady** [comment]
Awesome !
Thank you very much !
