### ISSUE TITLE
Request : Recording the angle and direction at the beginning of the record

### ISSUE THREAD

**Issue by FullHDReady** [jaszlo/Playerautoma#7]
Sorry english actually not my main language.

Actually when you wanna make a record, you will be always facing West direction and looking front of you, no matter what position you wanna start the record.

it will be cool if the mod can record the angle and the direction i'm facing at the beginning instead of be always facing weast and front of me.

Thank you !

**Comment by jaszlo** [comment]
Thank you for the feedback. 

The reason that I always center the player on the current block and face him in one direction is so that looping actually makes sense.

Could you give me a reason or a specific case in which this feature would be necessary? Because, I don't see why you can't just let the player face that specific direction after facing west.

If the reason is sufficent I will add an option i.e. toggle to turn off the default direction or maybe also set it so be some specific direction if enabled.

**Comment by FullHDReady** [comment]
Thanks for taking time to respond to me.

It's mainly about having a smoother transition during a 'replay loop' between two replays and making it feel less like a bot. 

Often, when a replay ends, the direction I'm facing is not not necessarily the West and therefore when the loop starts, there is a weird movement which necessarily starts from the West to go in the direction I want. 

If I finish a loop looking at the ground, this would be nice if at the start of the next loop I could start by looking directly at the ground.

**Comment by jaszlo** [comment]
I agree that it doesn't feel smooth when looping or even when just starting a replay. But it wouldn't feel smooth even if it would start at the position that you were looking at, at the start of the recording. It will always have that "cut" unless the recording ends with the looking direction it has started with or you're looking at the exact direction when starting a replay. The default looking direction at the start ensures that a looped recording will always have the default starting position and not diverge when looped many times. 

That being said, I will probably add the option to disable and set the default looking direction in the future. Probably in a new major realse (~v0.4). It's just not that important that I would add it in a smaller update.
As a compromise I might change that "cut" into a smooth transition to the default position in the next  minor updates.

From my understanding this is not a functional problem and rather a problem of the user experience not being as smooth as it could be. If however you have a usecase where you can only use the mod if the default direction is not set please let me know in another comment.

**Comment by FullHDReady** [comment]
i understand your point and i agree with, no worries !
it was just a personnal request and your answer is perfectly fine !

thank you.

**Comment by jaszlo** [comment]
The new [version](https://modrinth.com/mod/playerautoma/versions) allows for a lot of customization regarding the looking direction :)
