### ISSUE TITLE
Can I edit .rec files?

### ISSUE THREAD

**Issue by MRCUOGUO** [jaszlo/Playerautoma#9]
If it is possible to support the editing of .rec files, I would like to know how to edit them. If editing .rec files is not possible, I hope to have support for editing .rec files so that I can adjust the delay between operations.

**Comment by jaszlo** [comment]
The `.rec` files are just serialized Java Objects. When you store a recording, all that happens is that an object of [this](https://github.com/jaszlo/Playerautoma/blob/main/src/main/java/net/jasper/mod/util/data/Recording.java) class gets serialized.


I have been wanting to add something like that, but it seems like a really large addition. I could look into adding the option of storing the recording as some readable data format like `.json` as well as exporting/importing them. That would make them editable. 

I could make a dedicated application for edditing these files in the future. But I don't think I will add this feature nativly in minecraft itself.

If you have any further questions please let me know :)

**Comment by jaszlo** [comment]
Will be added with the next patch. Allready got it working [here](https://github.com/jaszlo/Playerautoma/commit/57b7b14132aca6dcbd7c45dcce190ed7a705f2f3) Still will need to add/fix some other stuff for the next release. But I will probably release it in the next view days

**Comment by jaszlo** [comment]
Release has been published that allows export as json. So you can now manually edit recording
